# Generated by Django 4.0.4 on 2023-05-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_customer_diposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='diposition',
            field=models.CharField(choices=[('RNR', 'RNR-Ringing'), ('HU', 'HU-hangup'), ('LD', 'LD-Live demo'), ('CB', 'CB-Call back'), ('NC', 'NC-Not connected'), ('CBWP', 'CBWP-Call back without presentation'), ('SW', 'SW-Switch off'), ('NI', 'NI-Not Intrested'), ('WN', 'NI—wrong number'), ('PD', 'PD-Paid'), ('DND', 'DND-Do not disturb'), ('None', 'None')], default='None', max_length=50),
        ),
    ]
