# Generated by Django 4.0.4 on 2023-05-29 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_customer_diposition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Lead',
        ),
    ]
