# Generated by Django 4.0.4 on 2023-06-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_leadhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadhistory',
            name='diposition',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
