# Generated by Django 4.0.4 on 2023-06-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_rename_diposition_leadhistory_disposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadhistory',
            name='disposition',
            field=models.CharField(default='None', max_length=50, null=True),
        ),
    ]
