# Generated by Django 4.0.3 on 2022-04-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_img',
            field=models.ImageField(default='SOME STRING', upload_to='uploads/'),
        ),
    ]
