# Generated by Django 4.0.3 on 2022-04-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_service_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_img',
            field=models.ImageField(default='', upload_to='static/assets/img/portfolio'),
        ),
    ]
