# Generated by Django 4.0.4 on 2023-06-04 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('breaks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='break',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_breaks', to=settings.AUTH_USER_MODEL),
        ),
    ]
