# Generated by Django 4.0.4 on 2023-06-04 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0002_break_assigned_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='break',
            name='assigned_user',
        ),
    ]
